use crate::parser::{SupportedFunction, UnsupportedFunction, rust_type_to_ts, rust_type_to_arg_type, rust_type_to_ret_type};
use anyhow::Result;
use std::fs;

pub fn generate(output_dir: &str, name: &str, supported: &[SupportedFunction], unsupported: &[UnsupportedFunction]) -> Result<()> {
    generate_toml(output_dir, name, supported, unsupported)?;
    generate_dts(output_dir, name, supported)?;
    generate_readme(output_dir, name)?;
    generate_deps_file(name)?;
    Ok(())
}

pub fn generate_empty(output_dir: &str, name: &str) -> Result<()> {
    println!("Generating files in: {}", output_dir);
    generate_toml(output_dir, name, &[], &[])?;
    println!("  ✓ ts-native.toml");
    generate_dts(output_dir, name, &[])?;
    println!("  ✓ index.d.ts");
    generate_readme(output_dir, name)?;
    println!("  ✓ README.md");
    generate_deps_file(name)?;
    Ok(())
}

fn generate_deps_file(name: &str) -> Result<()> {
    let ts_files = find_ts_files()?;
    if ts_files.is_empty() {
        println!("  (未找到 .ts 文件，跳过 .ts.toml 生成)");
        return Ok(());
    }
    for ts_file in &ts_files {
        let deps_path = format!("{}.toml", ts_file);
        if std::path::Path::new(&deps_path).exists() {
            let existing = fs::read_to_string(&deps_path)?;
            if existing.contains(&format!("\"{}\"", name)) {
                println!("  ({} 已包含 {}，跳过)", deps_path, name);
                continue;
            }
            let updated = add_dep_to_existing(&existing, name);
            fs::write(&deps_path, updated)?;
            println!("  ✓ {} (已更新)", deps_path);
        } else {
            let content = format!(
                "[dependencies]\ntsnp = [\"{}\"]\n",
                name
            );
            fs::write(&deps_path, content)?;
            println!("  ✓ {}", deps_path);
        }
    }
    Ok(())
}

fn find_ts_files() -> Result<Vec<String>> {
    let mut result = Vec::new();
    for entry in fs::read_dir(".")? {
        let entry = entry?;
        let path = entry.path();
        if let Some(ext) = path.extension() {
            if ext == "ts" || ext == "tsx" {
                if let Some(name) = path.file_name().map(|n| n.to_string_lossy().to_string()) {
                    result.push(name);
                }
            }
        }
    }
    Ok(result)
}

fn add_dep_to_existing(content: &str, name: &str) -> String {
    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let mut found_tsnp = false;
    let mut tsnp_idx = None;
    
    for (i, line) in lines.iter().enumerate() {
        if line.trim().starts_with("tsnp") {
            found_tsnp = true;
            tsnp_idx = Some(i);
            break;
        }
    }
    
    if found_tsnp {
        if let Some(idx) = tsnp_idx {
            let line = &lines[idx];
            if line.contains(&format!("\"{}\"", name)) {
                return content.to_string();
            }
            let new_line = if let Some(pos) = line.rfind(']') {
                format!("{}, \"{}\"]", line[..pos].to_string(), name)
            } else {
                line.clone()
            };
            lines[idx] = new_line;
        }
    } else {
        let deps_line = format!("tsnp = [\"{}\"]", name);
        let mut inserted = false;
        let mut new_lines = Vec::new();
        for line in &lines {
            new_lines.push(line.clone());
            if !inserted && line.trim() == "[dependencies]" {
                new_lines.push(deps_line.clone());
                inserted = true;
            }
        }
        if !inserted {
            new_lines.push(String::new());
            new_lines.push("[dependencies]".to_string());
            new_lines.push(deps_line);
        }
        lines = new_lines;
    }
    
    lines.join("\n")
}

fn generate_toml(output_dir: &str, name: &str, supported: &[SupportedFunction], unsupported: &[UnsupportedFunction]) -> Result<()> {
    let mut content = format!(
        r#"# ts-native Plugin Configuration
# Auto-generated by tsnp for crate '{}'
# 
# This file defines the mapping between TypeScript function names and Rust FFI implementations.
# Edit this file to customize function mappings or add manual entries.
#
# Structure:
#   [package]     - Plugin metadata
#   [functions]   - TypeScript name → Rust function mapping
#   [link]        - Native library linkage settings

[package]
name = "tsnp-{}"
version = "0.1.0"
tsnpVersion = "0.1.0"

[functions]
"#,
        name, name
    );
    
    for func in supported {
        let args: Vec<String> = func.params.iter()
            .map(|p| rust_type_to_arg_type(p))
            .collect();
        let ret = rust_type_to_ret_type(&func.return_type);
        
        content.push_str(&format!(
            r#""{}" = {{ args = [{}], ret = "{}", impl_name = "{}" }}
"#,
            func.name,
            args.iter().map(|a| format!("\"{}\"", a)).collect::<Vec<_>>().join(", "),
            ret,
            func.name
        ));
    }
    
    if !unsupported.is_empty() {
        content.push_str("\n# Unable to auto-generate:\n");
        for func in unsupported {
            content.push_str(&format!(
                r#"# "{}" = {{ impl_name = "{}" }}
#   signature: {}
#   {}
"#,
                func.name, func.name, func.raw_signature, func.reason
            ));
        }
    }
    
    content.push_str(&format!(
        r#"
[link]
lib = "{}"
"#,
        name
    ));
    
    let toml_path = format!("{}/ts-native.toml", output_dir);
    fs::write(&toml_path, content)?;
    Ok(())
}

fn generate_dts(output_dir: &str, name: &str, supported: &[SupportedFunction]) -> Result<()> {
    let mut content = format!(
        r#"// TypeScript Type Definitions for ts-native Plugin
// Auto-generated by tsnp for crate '{}'
//
// This file provides TypeScript type definitions for Rust FFI functions.
// Import this module in your TypeScript code to get type safety and IDE autocomplete.
//
// Usage:
//   import {{ functionName }} from "tsnp-{}";

declare module "tsnp-{}" {{
"#,
        name, name, name
    );
    
    for func in supported {
        let params: Vec<String> = func.params.iter()
            .map(|p| rust_type_to_ts(p))
            .enumerate()
            .map(|(i, t)| format!("arg{}: {}", i, t))
            .collect();
        
        let ret = rust_type_to_ts(&func.return_type);
        
        content.push_str(&format!(
            "    export function {}({}): {};\n",
            func.name,
            params.join(", "),
            ret
        ));
    }
    
    content.push_str("}\n");
    
    let dts_path = format!("{}/index.d.ts", output_dir);
    fs::write(&dts_path, content)?;
    Ok(())
}

fn generate_readme(output_dir: &str, name: &str) -> Result<()> {
    let content = format!(
        r#"# tsnp-{}

**ts-native plugin for [{}](https://crates.io/crates/{})**

This directory contains auto-generated configuration files for using the `{}` Rust crate with ts-native runtime. These files enable TypeScript code to call Rust FFI functions directly without Node.js.

## Generated Files

| File | Description |
|------|-------------|
| `ts-native.toml` | Plugin configuration: function mappings, library linkage |
| `index.d.ts` | TypeScript type definitions for FFI functions |
| `README.md` | This documentation file |

## Quick Start

### 1. Add Rust Dependency

Add the crate to your project's `Cargo.toml`:

```toml
[dependencies]
{} = "0.1.0"
```

### 2. Build Native Library

Build your Rust project to generate the native library (`.dll` / `.so` / `.dylib`):

```bash
cargo build --release
```

### 3. Import in TypeScript

Use the generated type definitions in your TypeScript code:

```typescript
import {{ /* function names */ }} from "tsnp-{}";

// Example (replace with actual function names):
// const result = someFunction(arg1, arg2);
```

### 4. Configure ts-native Runtime

Ensure ts-native runtime can locate the native library. The runtime will:
- Load the library specified in `[link].lib`
- Resolve function names according to `[functions]` mapping
- Handle type conversions between TypeScript and Rust

## Manual Configuration

If the auto-generated configuration is incomplete or incorrect, edit `ts-native.toml`:

### Adding Functions

```toml
[functions]
"tsFunctionName" = {{ impl_name = "rust_function_name" }}
```

### Changing Library Name

```toml
[link]
lib = "custom-lib-name"
```

### Multiple Libraries

```toml
[link]
libs = ["lib1", "lib2"]
```

## Type Mapping Reference

| Rust Type | TypeScript Type |
|-----------|-----------------|
| `i32`, `u32`, `i64`, `u64` | `number` |
| `f32`, `f64` | `number` |
| `*const c_char`, `*mut c_char` | `string` |
| `*const T`, `*mut T` | `number` (pointer) |
| `()` | `void` |

**Unsupported Types** (require manual wrappers):
- `Option<T>`, `Result<T, E>`
- `Vec<T>`, `String` (by value)
- Structs with non-POD fields
- Callbacks / function pointers

## Troubleshooting

### "Library not found"
- Ensure the Rust crate is built with `cargo build --release`
- Check that `[link].lib` matches the actual library name
- Verify library search path configuration in ts-native runtime

### "Function not found"
- Verify the function is marked with `#[no_mangle]` and `extern "C"`
- Check the function name in `[functions]` matches exactly
- Use `nm` or `objdump` to list exported symbols

### Type mismatch errors
- Review the type mapping table above
- Add manual wrappers for unsupported types
- Check that Rust and TypeScript types are compatible

## Regenerating Files

To regenerate these files with updated FFI functions:

```bash
cargo tsnp gen {}
```

## Links

- [ts-native Runtime](https://github.com/itszzl-sudo/ts-native)
- [Original crate on crates.io](https://crates.io/crates/{})
- [tsnp Tool](https://github.com/itszzl-sudo/tsnp)

---
*Generated by tsnp - TypeScript Native Plugin Generator*
"#,
        name, name, name, name, name, name, name, name
    );
    
    let readme_path = format!("{}/README.md", output_dir);
    fs::write(&readme_path, content)?;
    Ok(())
}
