use crate::parser::{SupportedFunction, UnsupportedFunction, rust_type_to_ts, rust_type_to_arg_type, rust_type_to_ret_type};
use anyhow::Result;
use std::fs;

pub fn generate(output_dir: &str, name: &str, supported: &[SupportedFunction], unsupported: &[UnsupportedFunction]) -> Result<()> {
    generate_main_toml(output_dir, name, supported, unsupported)?;
    generate_platform_toml(output_dir, name)?;
    generate_dts(output_dir, name, supported)?;
    generate_c_placeholder(output_dir, name)?;
    generate_readme(output_dir, name)?;
    generate_deps_file(name)?;
    Ok(())
}

pub fn generate_empty(output_dir: &str, name: &str) -> Result<()> {
    println!("Generating files in: {}", output_dir);
    generate_main_toml(output_dir, name, &[], &[])?;
    println!("  ✓ ts-native.toml");
    generate_platform_toml(output_dir, name)?;
    println!("  ✓ ts-native-win.toml");
    println!("  ✓ ts-native-linux.toml (placeholder)");
    println!("  ✓ ts-native-macos.toml (placeholder)");
    generate_dts(output_dir, name, &[])?;
    println!("  ✓ index.d.ts");
    generate_c_placeholder(output_dir, name)?;
    println!("  ✓ {}_win.c (placeholder)", name.replace("-", "_"));
    generate_readme(output_dir, name)?;
    println!("  ✓ README.md");
    generate_deps_file(name)?;
    Ok(())
}

fn generate_deps_file(name: &str) -> Result<()> {
    let ts_files = find_ts_files()?;
    if ts_files.is_empty() {
        println!("  (未找到 .ts 文件，跳过 .ts.toml 生成)");
        return Ok(());
    }
    for ts_file in &ts_files {
        let deps_path = format!("{}.toml", ts_file);
        if std::path::Path::new(&deps_path).exists() {
            let existing = fs::read_to_string(&deps_path)?;
            if existing.contains(&format!("\"{}\"", name)) {
                println!("  ({} 已包含 {}，跳过)", deps_path, name);
                continue;
            }
            let updated = add_dep_to_existing(&existing, name);
            fs::write(&deps_path, updated)?;
            println!("  ✓ {} (已更新)", deps_path);
        } else {
            let content = format!(
                "[dependencies]\ntsnp = [\"{}\"]\n",
                name
            );
            fs::write(&deps_path, content)?;
            println!("  ✓ {}", deps_path);
        }
    }
    Ok(())
}

fn find_ts_files() -> Result<Vec<String>> {
    let mut result = Vec::new();
    for entry in fs::read_dir(".")? {
        let entry = entry?;
        let path = entry.path();
        if let Some(ext) = path.extension() {
            if ext == "ts" || ext == "tsx" {
                if let Some(name) = path.file_name().map(|n| n.to_string_lossy().to_string()) {
                    result.push(name);
                }
            }
        }
    }
    Ok(result)
}

fn add_dep_to_existing(content: &str, name: &str) -> String {
    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let mut found_tsnp = false;
    let mut tsnp_idx = None;
    
    for (i, line) in lines.iter().enumerate() {
        if line.trim().starts_with("tsnp") {
            found_tsnp = true;
            tsnp_idx = Some(i);
            break;
        }
    }
    
    if found_tsnp {
        if let Some(idx) = tsnp_idx {
            let line = &lines[idx];
            if line.contains(&format!("\"{}\"", name)) {
                return content.to_string();
            }
            let new_line = if let Some(pos) = line.rfind(']') {
                format!("{}, \"{}\"]", line[..pos].to_string(), name)
            } else {
                line.clone()
            };
            lines[idx] = new_line;
        }
    } else {
        let deps_line = format!("tsnp = [\"{}\"]", name);
        let mut inserted = false;
        let mut new_lines = Vec::new();
        for line in &lines {
            new_lines.push(line.clone());
            if !inserted && line.trim() == "[dependencies]" {
                new_lines.push(deps_line.clone());
                inserted = true;
            }
        }
        if !inserted {
            new_lines.push(String::new());
            new_lines.push("[dependencies]".to_string());
            new_lines.push(deps_line);
        }
        lines = new_lines;
    }
    
    lines.join("\n")
}

fn generate_toml(output_dir: &str, name: &str, supported: &[SupportedFunction], unsupported: &[UnsupportedFunction]) -> Result<()> {
    let mut content = format!(
        r#"# ts-native Plugin Configuration
# Auto-generated by tsnp for crate '{}'
# 
# This file defines the mapping between TypeScript function names and Rust FFI implementations.
# Edit this file to customize function mappings or add manual entries.
#
# Structure:
#   [package]     - Plugin metadata
#   [signatures]  - TypeScript function signatures
#   [includes]    - Platform config file references

[package]
name = "tsnp-{}"
version = "0.1.0"
# priority = 0  # Optional: plugin priority (supports decimals, negative numbers)

# Platform config file references
[includes]
win = "ts-native-win.toml"
linux = "ts-native-linux.toml"
macos = "ts-native-macos.toml"

# TypeScript function signatures
[signatures]
"#,
        name, name
    );
    
    for func in supported {
        let args: Vec<String> = func.params.iter()
            .map(|p| rust_type_to_ts(p))
            .collect();
        let ret = rust_type_to_ret_type(&func.return_type);
        
        // Build signature string
        let signature = format!("function({}): {}", args.join(", "), ret);
        
        content.push_str(&format!(
            r#""{}" = "{}"
"#,
            func.name,
            signature
        ));
    }
    
    if !unsupported.is_empty() {
        content.push_str("\n# Unable to auto-generate (unsupported types):\n");
        for func in unsupported {
            content.push_str(&format!(
                r#"# "{}" = "function(...): ..."
#   Raw: {}
#   Reason: {}
"#,
                func.name, func.raw_signature, func.reason
            ));
        }
    }
    
    content.push_str(&format!(
        r#"
# Build configuration
[build]
warn_on_missing = true
error_on_mismatch = true
"#
    ));
    
    let toml_path = format!("{}/ts-native.toml", output_dir);
    fs::write(&toml_path, content)?;
    Ok(())
}

fn generate_main_toml(output_dir: &str, name: &str, supported: &[SupportedFunction], unsupported: &[UnsupportedFunction]) -> Result<()> {
    generate_toml(output_dir, name, supported, unsupported)
}

fn generate_platform_toml(output_dir: &str, name: &str) -> Result<()> {
    // Windows platform config
    let win_content = format!(
        r#"# Windows Platform Configuration
# Auto-generated by tsnp for plugin '{}'

[platform]
name = "Windows"
os = "win"
arch = ["x86_64", "arm64"]
description = "Windows platform"

# Add your library dependencies here
# Example:
# [libs.bcrypt]
# description = "Windows CNG Cryptographic API"
# required = true
# header = "<bcrypt.h>"
#
# [libs.bcrypt.functions]
# "function_name" = {{
#     impl_name = "c_function_name",
#     enabled = true,
#     system = "SystemAPI",
#     args = ["string"],
#     ret = "string",
#     description = "Function description"
# }}
"#,
        name
    );
    
    let win_path = format!("{}/ts-native-win.toml", output_dir);
    fs::write(&win_path, win_content)?;
    
    // Linux platform config (placeholder)
    let linux_content = format!(
        r#"# Linux Platform Configuration (Placeholder)
# Auto-generated by tsnp for plugin '{}'

[platform]
name = "Linux"
os = "linux"
arch = ["x86_64", "arm64"]
description = "Linux platform (not yet implemented)"

# TODO: Add Linux library dependencies
"#,
        name
    );
    
    let linux_path = format!("{}/ts-native-linux.toml", output_dir);
    fs::write(&linux_path, linux_content)?;
    
    // macOS platform config (placeholder)
    let macos_content = format!(
        r#"# macOS Platform Configuration (Placeholder)
# Auto-generated by tsnp for plugin '{}'

[platform]
name = "macOS"
os = "macos"
arch = ["x86_64", "arm64"]
description = "macOS platform (not yet implemented)"

# TODO: Add macOS library dependencies
"#,
        name
    );
    
    let macos_path = format!("{}/ts-native-macos.toml", output_dir);
    fs::write(&macos_path, macos_content)?;
    
    Ok(())
}

fn generate_c_placeholder(output_dir: &str, name: &str) -> Result<()> {
    let c_name = name.replace("-", "_");
    
    // Windows C file placeholder
    let win_c_content = format!(
        r#"// Windows Implementation for {}
// Auto-generated by tsnp
// TODO: Implement your platform-specific functions here

#include <windows.h>

// Example:
// double crypto_md5(double data_val) {{
//     const char* input = js_string_unpack(data_val);
//     // ... implementation ...
//     return js_string_new(hash, len);
// }}
"#,
        name
    );
    
    let win_c_path = format!("{}/{}_win.c", output_dir, c_name);
    fs::write(&win_c_path, win_c_content)?;
    
    // Linux C file placeholder
    let linux_c_content = format!(
        r#"// Linux Implementation for {} (Placeholder)
// Auto-generated by tsnp
// TODO: Implement Linux-specific functions here
"#,
        name
    );
    
    let linux_c_path = format!("{}/{}_linux.c", output_dir, c_name);
    fs::write(&linux_c_path, linux_c_content)?;
    
    // macOS C file placeholder
    let macos_c_content = format!(
        r#"// macOS Implementation for {} (Placeholder)
// Auto-generated by tsnp
// TODO: Implement macOS-specific functions here
"#,
        name
    );
    
    let macos_c_path = format!("{}/{}_macos.c", output_dir, c_name);
    fs::write(&macos_c_path, macos_c_content)?;
    
    Ok(())
}

fn generate_dts(output_dir: &str, name: &str, supported: &[SupportedFunction]) -> Result<()> {
    let mut content = format!(
        r#"// TypeScript Type Definitions for ts-native Plugin
// Auto-generated by tsnp for crate '{}'
//
// This file provides TypeScript type definitions for Rust FFI functions.
// Import this module in your TypeScript code to get type safety and IDE autocomplete.
//
// Usage:
//   import {{ functionName }} from "tsnp-{}";

declare module "tsnp-{}" {{
"#,
        name, name, name
    );
    
    for func in supported {
        let params: Vec<String> = func.params.iter()
            .map(|p| rust_type_to_ts(p))
            .enumerate()
            .map(|(i, t)| format!("arg{}: {}", i, t))
            .collect();
        
        let ret = rust_type_to_ts(&func.return_type);
        
        content.push_str(&format!(
            "    export function {}({}): {};\n",
            func.name,
            params.join(", "),
            ret
        ));
    }
    
    content.push_str("}\n");
    
    let dts_path = format!("{}/index.d.ts", output_dir);
    fs::write(&dts_path, content)?;
    Ok(())
}

fn generate_readme(output_dir: &str, name: &str) -> Result<()> {
    let content = format!(
        r#"# tsnp-{}

**ts-native plugin for [{}](https://crates.io/crates/{})**

This directory contains auto-generated configuration files for using the `{}` Rust crate with ts-native runtime. These files enable TypeScript code to call Rust FFI functions directly without Node.js.

## Generated Files

| File | Description |
|------|-------------|
| `ts-native.toml` | Main plugin config: package info, signatures, platform references |
| `ts-native-win.toml` | Windows platform: library dependencies and function implementations |
| `ts-native-linux.toml` | Linux platform config (placeholder) |
| `ts-native-macos.toml` | macOS platform config (placeholder) |
| `{}_win.c` | Windows C implementation |
| `{}_linux.c` | Linux C implementation (placeholder) |
| `{}_macos.c` | macOS C implementation (placeholder) |
| `index.d.ts` | TypeScript type definitions for FFI functions |
| `README.md` | This documentation file |

## Quick Start

### 1. Add Rust Dependency

Add the crate to your project's `Cargo.toml`:

```toml
[dependencies]
{} = "0.1.0"
```

### 2. Configure Platform Functions

Edit `ts-native-win.toml` to define your function implementations:

```toml
[libs.bcrypt]
description = "Windows CNG API"
required = true

[libs.bcrypt.functions]
"my_function" = {{ 
    impl_name = "my_function",
    enabled = true,
    system = "SystemAPI",
    args = ["string"],
    ret = "string"
}}
```

### 3. Implement C Functions

Edit `{}_win.c` to implement your functions:

```c
#include <windows.h>

// External functions from runtime
extern double js_string_new(const char* data, unsigned int len);
extern const char* js_string_unpack(double val);

double my_function(double data_val) {{
    const char* input = js_string_unpack(data_val);
    // ... your implementation ...
    return js_string_new(result, len);
}}
```

### 4. Build Native Library

Build your Rust project to generate the native library:

```bash
cargo build --release
```

### 5. Import in TypeScript

Use the generated type definitions in your TypeScript code:

```typescript
import {{ myFunction }} from "tsnp-{}";

// Example:
const result = myFunction("data");
```

## Cross-Platform Strategy

### Current: Windows Only
```
{}_win.c      ← Full implementation ✅
{}_linux.c    ← Empty placeholder
{}_macos.c    ← Empty placeholder
```

### Future: Full Cross-Platform
```
{}_win.c      ← Windows implementation (bcrypt)
{}_linux.c    ← Linux implementation (OpenSSL)
{}_macos.c    ← macOS implementation (CommonCrypto)
```

## Configuration Reference

### Main Config (ts-native.toml)

```toml
[package]
name = "tsnp-{}"
version = "0.1.0"
priority = 0  # Optional: plugin priority (supports decimals, negative numbers)

[includes]
win = "ts-native-win.toml"
linux = "ts-native-linux.toml"
macos = "ts-native-macos.toml"

[signatures]
"my_function" = "function(data: string): string"

[build]
warn_on_missing = true
error_on_mismatch = true
```

### Platform Config (ts-native-win.toml)

```toml
[platform]
name = "Windows"
os = "win"
arch = ["x86_64", "arm64"]

[libs.bcrypt]
description = "Windows CNG API"
required = true

[libs.bcrypt.functions]
"my_function" = {{
    impl_name = "my_function",
    enabled = true,  # Only one enabled=true per function
    system = "SystemAPI",
    args = ["string"],
    ret = "string"
}}
```

## Type Mapping Reference

| Rust Type | TypeScript Type |
|-----------|-----------------|
| `i32`, `u32`, `i64`, `u64` | `number` |
| `f32`, `f64` | `number` |
| `*const c_char`, `*mut c_char` | `string` |
| `*const T`, `*mut T` | `number` (pointer) |
| `()` | `void` |

**Unsupported Types** (require manual wrappers):
- `Option<T>`, `Result<T, E>`
- `Vec<T>`, `String` (by value)
- Structs with non-POD fields
- Callbacks / function pointers

## Troubleshooting

### "Library not found"
- Ensure the Rust crate is built with `cargo build --release`
- Check that library names match in platform config
- Verify library search path configuration in ts-native runtime

### "Function not found"
- Verify the function is marked with `#[no_mangle]` and `extern "C"`
- Check the function name in `[libs.*.functions]` matches exactly
- Use `nm` or `objdump` to list exported symbols

### Type mismatch errors
- Review the type mapping table above
- Add manual wrappers for unsupported types
- Check that Rust and TypeScript types are compatible

### Multiple implementations enabled
- Same function can only have one `enabled=true` per platform
- Set `enabled=false` for all but one implementation

## Regenerating Files

To regenerate these files with updated FFI functions:

```bash
cargo tsnp gen {}
```

## Links

- [ts-native Runtime](https://github.com/itszzl-sudo/ts-native)
- [Original crate on crates.io](https://crates.io/crates/{})
- [tsnp Tool](https://github.com/itszzl-sudo/tsnp)

---
*Generated by tsnp - TypeScript Native Plugin Generator*
"#,
        name, name, name, name,  // 1-4: title, crate link x2, crate name
        name.replace("-", "_"), name.replace("-", "_"), name.replace("-", "_"),  // 5-7: C file names
        name,  // 8: Cargo.toml dep
        name.replace("-", "_"),  // 9: C impl file
        name,  // 10: import module
        name.replace("-", "_"), name.replace("-", "_"), name.replace("-", "_"),  // 11-13: cross-platform strategy current
        name.replace("-", "_"), name.replace("-", "_"), name.replace("-", "_"),  // 14-16: cross-platform strategy future
        name,  // 17: main config name
        name,  // 18: gen command
        name  // 19: crates.io link
    );
    
    let readme_path = format!("{}/README.md", output_dir);
    fs::write(&readme_path, content)?;
    Ok(())
}
